add npk_install
Signed-off-by: Ishimoto Shinobu <nagakamira@gmail.com>

diff --git a/src/neko/neko b/src/neko/neko
--- a/src/neko/neko
+++ b/src/neko/neko
@@ -6,9 +6,9 @@ unalias -a
 
 pushd() { command pushd "$1" > /dev/null; }
 popd() { command popd "$1" > /dev/null; }
-msg() { printf "\033[1;32m ->\033[0m %s\n" "$@"; }
-warn() { printf "\033[1;33m ->\033[0m %s\n" "$@"; }
-die() { printf "\033[1;31m ->\033[0m %s\n" "$@"; exit 1; }
+msg() { printf "\033[1;34m::\033[0m %s\n" "$@"; }
+warn() { printf "\033[1;33m::\033[0m %s\n" "$@"; }
+die() { printf "\033[1;31m::\033[0m %s\n" "$@"; exit 1; }
 
 usage() { exit 0; }
 
@@ -23,24 +23,84 @@ get_filename() {
 
 	if echo "$1" | grep -q -E '^((https|http|ftp|rtsp|mms|file)?:\/\/).+'; then
 		tgt="$(basename $1)"
-		echo "$srcdest/$tgt"
+		echo "$SRCDEST/$tgt"
 	else
 		echo "$1"
 	fi
 }
 
-comment_variable() {
+create_zip() {
+	python3 <<-EOF
+		import npk_archive as NekoArchive
+		NekoArchive.CreateZipArchive("$1", "$2")
+	EOF
+}
+
+create_xz() {
+	python3 <<-EOF
+		import npk_archive as NekoArchive
+		NekoArchive.CreateXZArchive("$1", "$2")
+	EOF
+}
+
+unpack_zip() {
+	python3 <<-EOF
+		import npk_archive as NekoArchive
+		NekoArchive.UnpackZipArchive("$1", "$2")
+	EOF
+}
+
+unpack_xz() {
+	python3 <<-EOF
+		import npk_archive as NekoArchive
+		NekoArchive.UnpackXZArchive("$1", "$2")
+	EOF
+}
+
+list_zip() {
+	python3 <<-EOF
+		import npk_archive as NekoArchive
+		NekoArchive.ListZipContents("$1")
+	EOF
+}
+
+list_xz() {
+	python3 <<-EOF
+		import npk_archive as NekoArchive
+		NekoArchive.ListXZContents("$1")
+	EOF
+}
+
+parse_comment() {
 	python3 <<-EOF
 		import npk_parse as NekoParse
 		NekoParse.CommentVariable("$1", "$2")
 	EOF
 }
 
-json_variable() {
+parse_json() {
 	python3 <<-EOF
 		import npk_parse as NekoParse
 		NekoParse.JsonVariable("$1", "$2", "$3")
 	EOF
+}
+
+list_subtract() {
+	(
+		cat "$1" "$2" | sort | uniq -u
+		cat "$1"
+	) | sort | uniq -d
+}
+
+list_uninstall() {
+	local f p
+	local files=$(sort -r "$1" | sed 's:^:'"${ROOTDIR}/"': ; s:/^[^\.]\./::g; s:/\{2,\}:/:g; s:/\./:/:g')
+	if [ -z "$DRYRUN" ] ; then
+		echo "$files" | tr '\n' '\0' | xargs -0 rm 2>/dev/null
+		echo "$files" | tr '\n' '\0' | xargs -0 rmdir 2>/dev/null
+		[ "$2" ] && echo "$files" >> "$2"
+	fi
+	return 0
 }
 
 source_config() {
@@ -68,13 +128,13 @@ source_recipe() {
 
 	source "$myport"
 
-	depends="$(comment_variable $myport "Depends on")"
-	conflicts="$(comment_variable $myport "Conflicts with")"
-	summary="$(comment_variable $myport "Description")"
-	url="$(comment_variable $myport "URL")"
-	section="$(comment_variable $myport "Section")"
-	priority="$(comment_variable $myport "Priority")"
-	maintainer="$(comment_variable $myport "Maintainer" | sed -e 's/, / /g' | sed -e 's/ at /@/g' | sed -e 's/ dot /./')"
+	depends="$(parse_comment $myport "Depends on")"
+	conflicts="$(parse_comment $myport "Conflicts with")"
+	summary="$(parse_comment $myport "Description")"
+	url="$(parse_comment $myport "URL")"
+	section="$(parse_comment $myport "Section")"
+	priority="$(parse_comment $myport "Priority")"
+	maintainer="$(parse_comment $myport "Maintainer" | sed -e 's/, / /g' | sed -e 's/ at /@/g' | sed -e 's/ dot /./')"
 
 	if [ "$bootstrap" = "yes" ]; then
 		if [ -z "$summary" ]; then
@@ -354,11 +414,11 @@ create_package() {
 	pushd "$WORK"
 		pushd "$PKG"
 			msg "Compressing package data"
-			create_xz . "$WORK"/data.tar.xz
+			create_xz . "$WORK"/install.tar.xz
 
 			find $(ls) >> "$WORK"/files.txt
 
-			toinclude+=" data.tar.xz files.txt"
+			toinclude+=" install.tar.xz files.txt"
 		popd
 
 		msg "Generating metadata"
@@ -389,10 +449,10 @@ create_package() {
 			toinclude+=" backup"
 		fi
 
-		if [ -f "$topdir/install.py" ]; then
-			install -Dm0755 "$topdir/install.py" "$WORKDIR/install.py"
+		if [ -f "$topdir/install" ]; then
+			install -Dm0755 "$topdir/install" "$WORKDIR/install"
 
-			toinclude+=" install.py"
+			toinclude+=" install"
 		fi
 
 		for i in $toinclude; do
@@ -413,14 +473,14 @@ create_package() {
 npk_build() {
 	source_recipe
 
-	if [ -z "$pkgdest" ]; then
-		pkgdest="$topdir"
+	if [ -z "$PKGDEST" ]; then
+		PKGDEST="$topdir"
 	fi
-	if [ -z "$srcdest" ]; then
-		srcdest="$topdir"
+	if [ -z "$SRCDEST" ]; then
+		SRCDEST="$topdir"
 	fi
 
-	TARGET="$pkgdest/$name-$version-$release.$BARCH.npk"
+	TARGET="$PKGDEST/$name-$version-$release.$BARCH.npk"
 
 	if [ "$force" = "yes" ]; then
 		rm -rf "$TARGET"
@@ -463,12 +523,169 @@ npk_build() {
 		fi
 	else
 		warn "Package have already built"
+		return 0
 	fi
+}
+
+run_backup() {
+	local backup="$1"
+	local action="$2"
+	local mybackup
+
+	if [ -f "$backup" ]; then
+		case $action in
+			save)
+				msg "Saving files for backup"
+				while IFS= read -r mybackup; do
+					if [ -f "$ROOTDIR/$mybackup" ]; then
+						mv "$ROOTDIR/$mybackup" "$ROOTDIR/$mybackup.bak" || die "Failed to save file: ${mybackup}"
+					fi
+				done < "$backup"
+				;;
+			restore)
+				msg "Restoring old files"
+				while IFS= read -r mybackup; do
+					if [ -f "$ROOTDIR/$mybackup.bak" ]; then
+						if [ -f "$ROOTDIR/$mybackup" ]; then
+							mv "$ROOTDIR/$mybackup" "$ROOTDIR/$mybackup.new" || die "Failed to save new file: ${mybackup}"
+						fi
+						mv "$ROOTDIR/$mybackup.bak" "$ROOTDIR/$mybackup" || die "Failed to restore file: ${mybackup}"
+					fi
+				done < "$backup"
+				;;
+		esac
+	fi
+}
+
+run_scripts() {
+	local script="$1"
+	local action="$2"
+
+	if [ -x "$script" ]; then
+		cp "$script" "$ROOTDIR/install"
+		msg "Running $action script"
+		xchroot "${ROOTDIR}/" /install $action
+		rm -rf "$ROOTDIR/install"
+	fi
+}
+
+npk_install() {
+	if [ "$TARGET" ]; then
+		local pkg="$TARGET"
+	else
+		local pkg="$1"
+	fi
+
+	[ ! -f "$pkg" ] && die "Your package file was not found or not specified"
+	[ "${pkg##*.}" != "npk" ] && die "This file does not end in .npk"
+
+	[ -z "$(list_zip $pkg | grep -oh 'manifest.json')" ] && die "It is not a neko package"
+
+	if [ "$rootdir" ] && [ ! -d "$rootdir" ]; then
+		mkdir -p "$rootdir"
+	fi
+
+	tmpdir="$(mktemp -d)" || die "Couldn't create a temporary directory"
+	unpack_zip "$tmpdir" "$pkg"
+
+	local localname="$(parse_json $tmpdir/manifest.json summary name)"
+	local localver="$(parse_json $tmpdir/manifest.json summary version)"
+	local localrel="$(parse_json $tmpdir/manifest.json summary release)"
+
+	[ -z "$localname" ] && die "Your package is broken"
+
+	if [ -f "${rootdir}${DBDIR}/$localname/manifest.json" ]; then
+		if [ "$needed" = "yes" ]; then
+			warn "$localname: This package has been already installed"
+			return 0
+		else
+			msg "Updating package: $localname"
+			local update="true"
+		fi
+	else
+		msg "Installing package: $localname"
+		local update="false"
+	fi
+
+	trap "" INT
+
+	if [ "$force" != "yes" ] && [ "$update" != "true" ]; then
+		msg "Checking for file conflicts"
+		if [ ! -f "${rootdir}${DBDIR}/$localname/manifest.json" ]; then
+			for fileconflicts in $(list_xz $tmpdir/install.tar.xz); do
+				if [ -f "$rootdir/$fileconflicts" ] || [ -L "$rootdir/$fileconflicts" ]; then
+					echo "$fileconflicts" >> /tmp/conflicts
+				fi
+			done
+			if [ -f "/tmp/conflicts" ]; then
+				warn "Following files couldn't be overwritten"
+				cat /tmp/conflicts
+				exit 1
+			fi
+		fi
+	fi
+
+	if [ "$scripts" != "no" ]; then
+		if [ -f "$tmpdir/install" ]; then
+			run_scripts "$tmpdir/install" pre-install
+		fi
+	fi
+	if [ "$backup" != "no" ]; then
+		if [ -f "$tmpdir/backup" ]; then
+			run_backup "$tmpdir/backup" save
+		fi
+	fi
+
+	msg "Extracting package"
+	unpack_xz "${rootdir}/" "$tmpdir/install.tar.xz"
+	if [ $? -ne 0 ]; then
+		die "Failed to extract package"
+	fi
+
+	if [ "$update" = "true" ]; then
+		if [ -f "$tmpdir/files.txt" ] && [ -f "${ROOTDIR}${DBDIR}/$localname/files" ]; then
+			msg -1 "Removing old files"
+			list_subtract "${ROOTDIR}${DBDIR}/$localname/files" "$tmpdir/files.txt" | list_uninstall - || true
+		fi
+	fi
+
+	if [ "$backup" != "no" ]; then
+		if [ -f "$tmpdir/backup" ]; then
+			run_backup "$tmpdir/backup" restore
+		fi
+	fi
+
+	if [ "$scripts" != "no" ]; then
+		if [ -f "$tmpdir/install" ]; then
+			run_scripts "$tmpdir/install" post-install
+		fi
+	fi
+
+	msg "Installing package info"
+	if [ "$update" = "true" ]; then
+		rm -rf "${rootdir}${DBDIR}/$localname"
+		mkdir -p "${rootdir}${DBDIR}/$localname"
+	else
+		mkdir -p "${rootdir}${DBDIR}/$localname"
+	fi
+
+	for files in manifest.json files.txt backup install; do
+		if [ -f "$tmpdir/$files" ]; then
+			install -Dm0644 "$tmpdir/$files" "${rootdir}${DBDIR}/$localname/$files"
+		fi
+	done
+
+	#run_triggers $localname
+
+	rm -rf "$tmpdir" "/tmp/conflicts" "$rootdir/install"
+	msg "Package was successfully installed"
+
+	trap INT
 }
 
 main() {
 	topdir="$PWD"
-	config="/etc/neko.config"
+	config="/etc/neko/make.conf"
 	OPTIONS=('emptydirs' 'strip' 'makeflags' 'locales' 'docs' 'ccache' 'libtool' '~bootstrap' '~embedded')
 
 	force="no"
